name: Terraform Apply

on:
  push:
    paths:
      - 'terraform/**'  # Runs only if Terraform files change
  workflow_dispatch:
    
jobs:
  terraform:
    name: Terraform Init & Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Zip Lambda function
        run: |
          cd terraform
          zip -r stop_ec2_lambda.zip stop_ec2_lambda.py
        shell: bash

      - name: Terraform Apply (auto-approve)
        run: terraform apply -auto-approve
        working-directory: terraform