name: Terraform Cleanup

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'The environment to apply (dev or prod)'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      bucket_name:
        description: 'Name of the s3 bucket to create.'
        required: true
  
jobs:
  terraform-cleanup:
    name: 'DESTROY Terraform'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v3

    - name: 'Terraform Init'
      run: terraform init
      working-directory: terraform

    - name: 'Terraform Apply Destroy'
      run: terraform destroy -var-file="${{ github.event.inputs.stage }}_config.tfvars" -var="bucket_name=${{ github.event.inputs.bucket_name }}" --auto-approve
      working-directory: terraform